CREATE DATABASE DEMO_08
CREATE TABLE NHANVIEN(
MANV VARCHAR(10) PRIMARY KEY,
HOTENNV NVARCHAR(50),
NAMLAMVIEC INT,
LUONG INT,
)

CREATE TABLE KHACHHANG(
MAKH VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50),
NGAYSINH DATE,
QUEQUAN NVARCHAR(20),
GTINH NVARCHAR(10),
)

CREATE TABLE DONDATHANG(
SOHD VARCHAR(10) PRIMARY KEY,
MAKH VARCHAR(10) REFERENCES KHACHHANG(MAKH),
MANV VARCHAR(10) REFERENCES NHANVIEN(MANV),
SANPHAM NVARCHAR(50),
)

INSERT INTO NHANVIEN  VALUES  ('N1',N'TRẦN AN NHIÊN',2013,6000000)
INSERT INTO NHANVIEN VALUES ('N2',N'LÊ BÌNH AN',2018,9000000)
INSERT INTO NHANVIEN VALUES ('N3',N'PHAN HUY VĂN',2020,5000000)

INSERT INTO KHACHHANG VALUES ('KH1',N'TRẦN BÌNH MINH','1979-5-1',N'HÀ NỘI','NAM')
INSERT INTO KHACHHANG VALUES ('KH2',N'KHỔNG TƯỚC','2000-3-8',N'HÀ TĨNH','NAM')
INSERT INTO KHACHHANG VALUES ('KH3',N'ĐẶNG NGA','1997-1-5',N'HÀ NỘI',N'NỮ')

INSERT INTO DONDATHANG VALUES ('H001','KH1','N1',N'SON MÔI')
INSERT INTO DONDATHANG VALUES ('H002','KH2','N2',N'KEM DƯỠNG')
INSERT INTO DONDATHANG VALUES ('H003','KH3','N2',N'TÚI')

SELECT * FROM KHACHHANG 
SELECT * FROM NHANVIEN 
SELECT * FROM DONDATHANG 

--Câu 2: Đưa ra thông tin: mã nv, hotenNV, luong đặt hàng cho khách hàng Khổng Tước. (1đ)
SELECT NHANVIEN.MANV,HOTENNV,LUONG FROM NHANVIEN 
JOIN DONDATHANG ON NHANVIEN.MANV=DONDATHANG.MANV
JOIN KHACHHANG ON KHACHHANG.MAKH=DONDATHANG.MAKH
WHERE HOTEN=N'KHỔNG TƯỚC'

--Câu 3: Đưa ra thông tin: Manv, HotenNV, lương của những nhân viên có năm làm việc>2012 và có tên là Nhiên 
SELECT MANV,HOTENNV,LUONG FROM NHANVIEN
WHERE NAMLAMVIEC >2012 AND HOTENNV LIKE N'%NHIÊN'

--Câu 4: Đưa ra thông tin nhân viên bán được nhiều sản phẩm nhất Thông tin hiển thị gồm có: Manv, Hoten, số lượng sản phẩm (1đ)
SELECT TOP 1 NHANVIEN.MANV,HOTENNV, 'SLSP'= COUNT(DONDATHANG.MANV) FROM NHANVIEN
JOIN DONDATHANG ON NHANVIEN.MANV=DONDATHANG.MANV 
GROUP BY NHANVIEN.MANV,HOTENNV
ORDER BY  COUNT(DONDATHANG.MANV) DESC 

--Câu 5: Đưa ra danh sách 2 khách hàng đầu tiên thông tin gồm :makh, hotenKH, tuổi của những khách hàng có quê là Hà Nội và sắp xếp giảm dần theo Hoten. (1đ)
SELECT TOP 2 MAKH,HOTEN, N'TUỔI'=YEAR(GETDATE())-YEAR(NGAYSINH) FROM KHACHHANG
WHERE QUEQUAN=N'HÀ NỘI'
ORDER BY HOTEN DESC 

--Câu 6: Thêm một bản ghi mới vào bảng dondathang,dữ liệu phù hợp( không được nhập giá trị null). 
INSERT INTO DONDATHANG VALUES ('H004','KH2','N2',N'MẶT NẠ')
SELECT * FROM DONDATHANG 

--Câu 7: Tăng 5% lương cho mọi nhân viên. 
UPDATE NHANVIEN SET LUONG= LUONG + LUONG * 0.05
SELECT * FROM NHANVIEN 

--Câu 8: Xóa nhân viên có tên là Văn. 
DELETE FROM NHANVIEN WHERE HOTENNV LIKE N'%VĂN'
SELECT * FROM NHANVIEN 