CREATE DATABASE DEMO_09
CREATE TABLE NHANVIEN(
MANV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR (50),
NGAYSINH DATE,
LUONG INT,
GTINH NVARCHAR(10),
)

CREATE TABLE DUAN(
MADA VARCHAR(10) PRIMARY KEY,
TENDA NVARCHAR(50),
NAMBATDAU INT,
)
CREATE TABLE CHAMCONG(
MANV VARCHAR(10) REFERENCES NHANVIEN(MANV),
MADA VARCHAR(10) REFERENCES DUAN(MADA),
SOGIO INT,
)

INSERT INTO NHANVIEN VALUES ('N01',N'LÊ VĂN TÈO','2002-3-1',19000000,'NAM')
INSERT INTO NHANVIEN VALUES ('N02',N'NGỌC GIÀU','1988-3-3',6000000,'NAM')
INSERT INTO NHANVIEN VALUES ('N03',N'ĐẶNG THỊ HIẾU','1996-1-5',60000000,N'NỮ')

INSERT INTO DUAN VALUES ('D1',N'PHẦN MỀM DẠY ONLINE',2021)
INSERT INTO DUAN VALUES ('D2',N'MẠNG AGENT',2022)
INSERT INTO DUAN VALUES ('D3',N'QUẢN LÝ SÁCH',2020)

INSERT INTO CHAMCONG VALUES ('N01','D1',220)
INSERT INTO CHAMCONG VALUES ('N03','D1',200)
INSERT INTO CHAMCONG VALUES ('N01','D3',90)

SELECT * FROM NHANVIEN
SELECT * FROM DUAN
SELECT * FROM CHAMCONG 

--Câu 2: Đưa ra thông tin: mã nv, hoten, ngaysinh của những nhân viên có lương >7000000 và giới tính là nữ. 
SELECT MANV,HOTEN,NGAYSINH FROM NHANVIEN
WHERE LUONG >7000000 AND GTINH=N'NỮ'

--Câu 3: Đưa ra thông tin: MaDA, TenDA của những dự án do nhân viên Ngọc giàu Tham gia
SELECT DUAN.MADA,TENDA FROM DUAN 
JOIN CHAMCONG ON CHAMCONG.MADA=DUAN.MADA
JOIN NHANVIEN ON NHANVIEN.MANV=CHAMCONG.MANV 
WHERE HOTEN=N'NGỌC GIÀU'

--Câu 4: Đưa ra thông tin nhân viên thông tin hiển thị gồm có: Manv, Hoten, tổng so gio của nhân viên có  tổng số giờ >300(1đ)
SELECT NHANVIEN.MANV,HOTEN,SUM(SOGIO) FROM NHANVIEN
JOIN CHAMCONG ON CHAMCONG.MANV=NHANVIEN.MANV 
GROUP BY NHANVIEN.MANV,HOTEN
HAVING SUM(SOGIO)>300

--Câu 5: Đưa ra thông tin: manv, hoten, số lượng dự án của mỗi nhân viên(1đ)
SELECT NHANVIEN.MANV,HOTEN,COUNT(CHAMCONG.MADA) AS 'SLDA' FROM NHANVIEN
JOIN CHAMCONG ON CHAMCONG.MANV=NHANVIEN.MANV
GROUP BY NHANVIEN.MANV,HOTEN

--Câu 6: Thêm một bản ghi mới vào bảng nhanvien,dữ liệu phù hợp( không được nhập giá trị null). 
INSERT INTO NHANVIEN VALUES ('N04',N'NGUYỄN VĂN A','1998-9-3',12000000,N'NỮ')
SELECT * FROM NHANVIEN 

---Câu 7: Thay đổi lại năm bắt đầu của dự án Mạng Agent thành 2019  (1đ)
UPDATE DUAN SET NAMBATDAU=2019 WHERE TENDA=N'MẠNG AGENT'
SELECT * FROM DUAN 

--Câu 8: Xóa dự án chưa thực hiện (1đ)
DELETE DUAN WHERE MADA NOT IN (SELECT MADA FROM CHAMCONG)
SELECT * FROM DUAN 