CREATE DATABASE DEMO_01
CREATE TABLE SINHVIEN(
MASV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50),
NGAYSINH DATE,
GIOITINH NVARCHAR(10),
)
INSERT INTO SINHVIEN VALUES ('DL001',N'NGUYỄN ĐẠI DƯƠNG','1989-11-12','NAM')
INSERT INTO SINHVIEN VALUES ('LT001',N'NGUYỄN THANH HOA','1988-01-02','NAM')
SELECT * FROM SINHVIEN 

CREATE TABLE MONHOC(
MAMH VARCHAR(10) PRIMARY KEY,
TENMONHOC NVARCHAR(50),
SOTINCHI INT,
)
INSERT INTO MONHOC VALUES ('SQL',N'CƠ SỞ DỮ LIỆU SQL SERVER',3)
INSERT INTO MONHOC VALUES ('XML',N'NGÔN NGỮ ĐÁNH DẤU MỞ RỘNG',4)
SELECT * FROM


CREATE TABLE DIEM(
MASV VARCHAR(10) REFERENCES SINHVIEN(MASV) NOT NULL,
MAMH VARCHAR(10) REFERENCES MONHOC(MAMH) NOT NULL,
DIEMTHI INT,
)
INSERT INTO DIEM VALUES ('DL001','SQL',8)
INSERT INTO DIEM VALUES ('DL001','XML',7)
INSERT INTO DIEM VALUES ('LT001','SQL',4)
SELECT * FROM DIEM 

--CÂU 2:: Hiển thị thông tin sinh viên gồm:
--Masv, hoten, ngaysinh, gioitinh, tuổi. (1 điểm)
SELECT MASV,HOTEN,NGAYSINH,GIOITINH,YEAR(GETDATE())-YEAR(NGAYSINH) AS N'TUỔI'
FROM SINHVIEN

--CÂU 3:: Hiển thị thông tin: Masv, hoten , Mamh và có điểm thi >=5. 
SELECT SINHVIEN.MASV,HOTEN,MAMH,DIEMTHI FROM SINHVIEN
JOIN DIEM ON SINHVIEN.MASV=DIEM.MASV 
WHERE DIEMTHI>=5

--CÂU 4:Hiển thị thông tin Masv, hoten và ĐTB của các sinh viên. 
--Trong đó ĐTB = (điểm thi  * Số tín chỉ)/tổng số tín chỉ. 
SELECT SINHVIEN.MASV,HOTEN,'ĐTB'=avg(DIEMTHI * SOTINCHI)/SUM(SOTINCHI) FROM SINHVIEN
JOIN DIEM ON DIEM.MASV=SINHVIEN.MASV
JOIN MONHOC ON MONHOC.MAMH=DIEM.MAMH 
GROUP BY SINHVIEN.MASV,HOTEN


--CÂU 5:Hiển thị thông tin Masv, hoten, Tuổi của sinh viên.
--Chỉ hiển thị  những sinh viên có tuổi lớn hơn 19 tuổi. 
SELECT MASV,HOTEN,YEAR(GETDATE())-YEAR(NGAYSINH) N'TUỔI' FROM SINHVIEN
WHERE YEAR(GETDATE())-YEAR(NGAYSINH) >19 

--CÂU 6:Chèn thêm một bản ghi mới vào bảng DIEM; 
--dữ liệu phù hợp nhưng không được nhập giá trị null. 
INSERT INTO DIEM VALUES ('LT001','XML',9)
SELECT * FROM DIEM 

--Câu 7: Cập nhật lại số tín chỉ môn SQL là 4 
UPDATE MONHOC SET SOTINCHI=4 WHERE MAMH='SQL'
SELECT * FROM MONHOC 

--Câu 8: Xóa những sinh viên có điểm thi <5 trong bảng DIEM.
SELECT * FROM SINHVIEN
JOIN DIEM ON SINHVIEN.MASV=DIEM.MASV
DELETE SINHVIEN WHERE (SELECT DIEMTHI FROM DIEM )<5

DELETE DIEM WHERE DIEMTHI<5
DELETE SINHVIEN WHERE SINHVIEN.MASV NOT IN
(SELECT MASV FROM DIEM WHERE DIEMTHI>=5)
SELECT * FROM SINHVIEN 
SELECT * FROM DIEM 