CREATE DATABASE DEMO_02
CREATE TABLE VANPHONG(
MAVP VARCHAR(10) PRIMARY KEY,
TENVP NVARCHAR(50),
)

INSERT INTO VANPHONG VALUES ('HC',N'HÀNH CHÍNH')
INSERT INTO VANPHONG VALUES ('CTSV',N'CỘNG TÁC SINH VIÊN')
SELECT * from vanphong 


CREATE TABLE NHANVIEN(
MANV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50),
NGAYSINH DATE,
GIOITINH NVARCHAR(10),
MAVP VARCHAR(10) REFERENCES VANPHONG(MAVP),
EMAIL VARCHAR(50),
SDT VARCHAR(10),
)

INSERT INTO NHANVIEN VALUES ('NV1',N'NGUYỄN ANH TUẤN','1989-11-12','NAM','HC','TUANNA5@FPT.EDE.VN','0988554303')
INSERT INTO NHANVIEN VALUES ('NV2',N'TRẦN THANH TÙNG','1988-01-02','NAM','CTSV','TUNGTT2@FPT.EDU.VN','0987792457')
INSERT INTO NHANVIEN VALUES ('NV3',N'KHÁNH LINH','2000-12-24',N'NỮ','HC','KHANHLINH2412@FPT.EDU.VN','0969852926')
SELECT * FROM NHANVIEN 


CREATE TABLE THANNHAN(
MATN VARCHAR(10) PRIMARY KEY,
HOTENTN NVARCHAR(50),
NGAYSINH DATE,
MOILH NVARCHAR(50),
MANV VARCHAR(10) REFERENCES NHANVIEN(MANV),
)

INSERT INTO THANNHAN VALUES ('TN01',N'NGUYỄN NGỌC ANH','1962-12-07',N'NGƯỜI THÂN','NV2')
INSERT INTO THANNHAN VALUES ('TN02',N'TRẦN TUẤN TÚ','1970-06-06',N'NGƯỜI QUEN','NV2')
SELECT * FROM THANNHAN 

--Câu 2: Hiển thị MaNV, HotenNV, MaVP và tháng sinh là tháng 8. 
SELECT MANV,HOTEN,MAVP FROM NHANVIEN
WHERE MONTH(NGAYSINH)=8

--Câu 3: Hiển thị MaNV, HotenNV, MaVP và Tuổi nhân viên.
--Chỉ hiển thị những nhân viên có tuổi lớn hơn 19. 
SELECT MANV,HOTEN,MAVP,YEAR(GETDATE())-YEAR(NGAYSINH) N'TUỔI' FROM NHANVIEN 
WHERE YEAR(GETDATE())-YEAR(NGAYSINH) >19

--Câu 4: Hiển thị thông tin: MaNV, HotenNV, TENVP, NGAYSINH, GIOITINH, EMAIL, SODT 
--và chỉ hiển thị những nhân viên họ “Trần”. 
SELECT MANV, HOTEN,TENVP,NGAYSINH,GIOITINH,EMAIL,SDT FROM NHANVIEN 
JOIN VANPHONG ON NHANVIEN.MAVP=VANPHONG.MAVP 
WHERE HOTEN LIKE N'TRẦN%'

--Câu 5: Hiển thị những nhân viên không có thân nhân
SELECT * FROM NHANVIEN 
 WHERE MANV NOT IN (SELECT MANV FROM THANNHAN)

--Câu 6: Thêm một bản ghi mới vào bảng VANPHONG;
--dữ liệu phù hợp nhưng không được nhập giá trị null. (1 điểm)
INSERT INTO VANPHONG VALUES ('SV',N'SINH VIÊN')
SELECT * FROM VANPHONG

--Câu 7: Cập nhật lại SODT của MaNV NV2 là 0987792444. 
UPDATE NHANVIEN SET SDT='0987792444'
WHERE MANV='NV2'
SELECT * FROM NHANVIEN 

--Câu 8: Xóa thông tin của NHANTHAN có mối liên hệ là “người quen” 
DELETE FROM THANNHAN WHERE MOILH=N'NGƯỜI QUEN'
SELECT * FROM THANNHAN 